### ISSUE TITLE
No check for `reskins` global (an optional dependency)

### ISSUE THREAD

**Issue by kirazy** [ickputzdirwech/SeaBlockCustomPack#2]
https://github.com/ickputzdirwech/SeaBlockCustomPack/blob/07c5de96a2321499ae2441a69c95bae7653c74e9/prototypes/icons.lua#L190

When I saw in your changelog that you force-enabled the Alien Science packs I thought this might be the case. Heads up, you don't protect against Artisanal Reskins not being present.

**Comment by kirazy** [comment]
As long as you check for reskins-bobs, you'll be fine.

If you want to be really fancy and support AR settings:
```LUA
if (reskins.bobs and reskins.bobs.triggers.technology.items) then
    ...
end
```

**Comment by ickputzdirwech** [comment]
I tend to forget these things all the time. :( Thanks for the letting me know. I fixed it right away

And by the way: thanks for your brilliant work! Your mods are amazing and I can't think about playing Sea Block without them any more.
